version: "3.7"

services:
  ssg:
    container_name: ssg
    build:
      context: ./ssg
      dockerfile: Dockerfile.dev
    volumes:
      - ./ssg/src:/ssg/src
      - ./ssg/test:/ssg/test
      - ./ssg/package.json:/ssg/package.json
      - ./ssg/tsconfig.json:/ssg/tsconfig.json
      - ./ssg/build:/ssg/build
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    env_file:
      - ./ssg.env
    command: npm start
