#!/bin/bash

# If repo url is not provided, set it to:
REPO="${1:-https://github.com/ponomarevandrey/my-website}"

cd ssg/build && \

git config --global user.email "info@andreyponomarev.ru"
git config --global user.name "Andrey Ponomarev"

git init && \
git add --all && \
git commit -m "Update website"
 
git remote add origin "$REPO"
git push --force \
         --set-upstream origin master
